# Generated by Django 6.0.7 on 2026-07-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia_completo', models.BooleanField(default=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_agenda', to='servicios.profesional')),
            ],
            options={
                'verbose_name': 'Bloqueo de agenda',
                'verbose_name_plural': 'Bloqueos de agenda',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('intervalo_minutos', models.PositiveIntegerField(default=30, help_text='Cantidad de minutos entre cada turno.')),
                ('activo', models.BooleanField(default=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='servicios.profesional')),
            ],
            options={
                'verbose_name': 'Horario de atención',
                'verbose_name_plural': 'Horarios de atención',
                'ordering': ['profesional', 'dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('profesional', 'dia_semana', 'hora_inicio', 'hora_fin'), name='horario_unico_profesional')],
            },
        ),
    ]
