# Generated by Django 6.0.7 on 2026-07-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_profesional_telefono_bloqueoagenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='banco',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profesional',
            name='identificacion_titular',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profesional',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profesional',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('AHORROS', 'Cuenta de ahorros'), ('CORRIENTE', 'Cuenta corriente'), ('OTRA', 'Otro tipo de cuenta')], max_length=20),
        ),
        migrations.AddField(
            model_name='profesional',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profesional',
            name='transferencia_habilitada',
            field=models.BooleanField(default=False, help_text='Permite que los usuarios paguen el anticipo mediante transferencia a este profesional.'),
        ),
    ]
