# Generated by Django 6.0.7 on 2026-07-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(default='Ecuador', max_length=80),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('DOCUMENTO_IDENTIDAD', 'Documento de identidad'), ('OTRO', 'Otro')], default='CEDULA', max_length=25),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=30, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=25),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('nacionalidad', 'tipo_documento', 'cedula'), name='documento_unico_por_nacionalidad'),
        ),
    ]
