# Generated by Django 6.0.7 on 2026-07-16 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria'), ('TARJETA', 'Tarjeta de débito o crédito')], max_length=20)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de comprobante o referencia de la transferencia.', max_length=120)),
                ('valor_servicio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE_VERIFICACION', 'Pendiente de verificación'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_VERIFICACION', max_length=30)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.especialidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='usuarios.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('profesional', 'fecha', 'hora'), name='cita_unica_profesional_fecha_hora')],
            },
        ),
    ]
