# Generated by Django 6.0.7 on 2026-07-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('usuarios', '0002_alter_paciente_options_paciente_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de verificación'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='usuarios.paciente', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
